from .room_1 import room_1
from .room_2 import room_2
from .room_3 import room_3
from .room_4 import room_4
from .room_5 import room_5
from .room_6 import room_6
from .room_7 import room_7
from .start_location import start
from .town import town
from .forest_1 import forest_1
from .forest_2 import forest_2
from .forest_3 import forest_3